---
- hosts: all

  vars:
   server: ""
   directory: ""
   dr: []

  tasks:
  
  - set_fact: directory="/home/umesh/NA_git_repo/{{ server }}"
  - command: "ls {{ directory }}"
    register: dir_out

  - set_fact:
     dr: "{{ dr}} + [ '{{ directory }}/{{ item }}' ]"
    with_items:
      - "{{dir_out.stdout_lines}}"
  
  - name: "git commit"
    shell: |
          git add -A && git commit -m "{{ tower_job_id }}"
          git push origin main
          git push server main
    args:
      chdir: "{{ item }}"
    with_items: 
    - "{{dr}}"
    ignore_errors: true
    
   


      

