---
- hosts: all
  #become: yes
  tasks:
   - name: git push on GitHub
     git:
      repo: 'https://github.com/shendeumesh57/test.git'
      #dest: /home/umesh/ttt
      clone: no
      update: no



   - name: Commit changes
     shell: |
            git config --global user.name "shendeumesh57"
            git config --global user.email "shendeumesh57@gmail.com"
            git add . && git commit -m "ansible  commit " && git push -u origin main


     args:
      chdir: /home/umesh/test

...
