---
- hosts: web

  vars:
   directory: /tmp/slb10777
   dr: []
   rv: []

  tasks:
  
  - command: "ls {{directory}}"
    register: dir_out

  - set_fact:
     dr: "{{ dr}} + [ '/tmp/slb10777/{{ item }}' ]"
    with_items:
      - "{{dir_out.stdout_lines}}"

  - name: This command will change the working directory to somedir/
    ansible.builtin.shell:
     cmd: git remote -v | grep push | awk '{print $2}' 
     chdir: "{{ item }}"
    with_items:
     - "{{ dr }}"
    

  