---
- hosts: web

  vars:
   directory: /tmp/slb10777
   dr: []


  tasks:
  
  - command: "ls {{directory}}"
    register: dir_out
  
  - debug:
     msg: "{{ item }}"
    with_items: "{{ dir_out }}"

    

  