---
   - name: "Checking GitHub repository --> /opt/cert"
     git:
      repo: "{{ repo_2 }}"
      clone: no
      update: no
   
   - name: 
     shell: 'git status'
     register: gt
     args:
      chdir: "{{ dir_2 }}"
   - name:  ## used for autocomit
     shell: 'date "+DATE:%D TIME:%T"'
     register: dt
   
   - block:
     - name: Git commit!
       shell: git add -A && git commit -m "{{ dt.stdout_lines }}" && git push -u origin main

       args:
        chdir: "{{ dir_2 }}"
      
     - name: "/opt/cert commit ---"
       debug:
        msg: "Successfully Commited"
     - name: checking apache configuration
       import_tasks: apache_config.yml
     
     - name: restarting apache
       import_tasks: service.yml
     
      
     when: gt.stdout_lines[-1] != "nothing to commit, working directory clean"


   
   - block:
     - name:
       debug:
        msg: "No changes found under the /opt/cert"
     when: gt.stdout_lines[-1] == "nothing to commit, working directory clean"



