---
# vars file for final_apache_pull
server: ""  # server name input parameter
directory: "" # directory name input parameter
directory_list: [] # converted string into list
dest_path: [] # absolute path for destination
base_path: "/opt/var/repos" # base path for dir
uname: ""
umail: ""
gpwd: ""
servers_repo_dir_path:
  - server: "server1"
    repo:
    - httpd: 'https://{{ uname | urlencode }}:{{ gpwd | urlencode }}@github.com/shendeumesh57/httpd.git'
      html: 'https://{{ uname | urlencode }}:{{ gpwd | urlencode }}@github.com/shendeumesh57/html.git'
     

  - server: "server2"
    repo:
    - httpd: 'https://github.com/shendeumesh57/prodA.git'
      html: 'https://github.com/shendeumesh57/prodB.git'
