---
- hosts: web
  vars:
  - repo: ""
  - repo_var: []
  - path: ['apache','httpd','html']
  - server: " "
  - git_and_path: {}

  tasks:

  - name: Fetching repo variables from jenkins
    set_fact:
     repo_var: "{{ repo_var}} + [ '{{ item }}' ]"
    with_items:
      - "{{repo.split(',')}}"
   
  - name: Directory creation 
    file:
     path: /tmp/{{ server }}/"{{ item[0] }}"
     state: directory
    with_nested:
    - "{{ path }}"
    - "{{ repo_var }}"
    when: (item[0] in item[1] )
   
  - set_fact:
     git_and_path: "{{ dict(repo | zip(repo_var)) | 
                   dict2items(key_name='repo_name', value_name='repo_path') }}"

  - name:
    git:
     repo: "{{ item.repo_name }}"
     dest: "{{ item.value_name }}" 
    with_items:
     - "{{ git_and_path }}"
    