---
   - name: "Checking GitHub repository"
     git:
      repo: "{{ repo_2 }}"
      clone: no
      update: no
   
   - name: 
     shell: 'git status'
     register: gt
     args:
      chdir: "{{ dir_2 }}"
   
   - block:
     - name: "Checking Git Status" 
       debug:
        msg: "Ignoring /opt/cert directory"
     
     - name: 
       meta: end_play
     when: gt.stdout_lines[-1] == "nothing to commit, working directory clean"

#############################################################################################################

## Git Commit
   
   - name:  ## used for autocomit
     shell: 'date "+DATE:%D TIME:%T"'
     register: dt

   - name: Commit changes
     shell: git add -A && git commit -m "{{ dt.stdout_lines }}" && git push -u origin main
           # git config --global user.name "{{userid.user_input}}"
           # git config --global user.email "{{emailid.user_input}}"
            
     args:
      chdir: "{{ dir_2 }}"
...

