---


  - name: check config apache
    command: /usr/sbin/httpd -t
    ignore_errors: yes
    register: op

  - block:
    - name: Apache config check
      debug:
       msg: "Apache configuration is invalid. Please check before re-running the playbook. Fix this manualy"
       
    - name:
      meta: end_play   
    when: 
      - op.stderr != "Syntax OK"



  